/*
* Copyright (c) 2021 ACOAUTO Team.
* All rights reserved.
*
* Detailed license information can be found in the LICENSE file.
*
* File: iotpi_key_jstruct.h iotpi_key JSON <-> C struct.
*
* Date: Tue Mar 01 2022 16:18:34 GMT+0800 (GMT+08:00)
*
* This file is automatically generated by the jstruct tool, please do not modify.
*
* Author: Han.hui <hanhui@acoinfo.com>
*
*/

#ifndef IOTPI_KEY_JSTRUCT_H
#define IOTPI_KEY_JSTRUCT_H

#include <stdint.h>
#include <stdbool.h>

#ifndef STRUCT_KEY_DEFINED
#define STRUCT_KEY_DEFINED
struct key {
	bool key1;
	bool key2;
	bool key3;
	void *json;
};
#endif /* STRUCT_KEY_DEFINED */

#ifdef __cplusplus
extern "C" {
#endif

/* Deserialize the JSON string into a structure 'key' */
bool iotpi_key_json_parse(struct key *, const char *, size_t);

/* Free iotpi_key_json_parse() buffer, Warning: string type member can no longer be used */
void iotpi_key_json_parse_free(struct key *);

/* Serialize the structure 'key' into a JSON string */
char *iotpi_key_json_stringify(struct key *);

/* Free iotpi_key_json_stringify() return value */
void iotpi_key_json_stringify_free(char *);

#ifdef __cplusplus
}
#endif

#endif /* IOTPI_KEY_JSTRUCT_H */
/*
 * end
 */
